#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-prefmod
Version  : 0.8.36
Release  : 48
URL      : https://cran.r-project.org/src/contrib/prefmod_0.8-36.tar.gz
Source0  : https://cran.r-project.org/src/contrib/prefmod_0.8-36.tar.gz
Summary  : Utilities to Fit Paired Comparison Models for Preferences
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-prefmod-lib = %{version}-%{release}
Requires: R-colorspace
Requires: R-gnm
BuildRequires : R-colorspace
BuildRequires : R-gnm
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-prefmod package.
Group: Libraries

%description lib
lib components for the R-prefmod package.


%prep
%setup -q -n prefmod
pushd ..
cp -a prefmod buildavx2
popd
pushd ..
cp -a prefmod buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737153189

%install
export SOURCE_DATE_EPOCH=1737153189
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/prefmod/CITATION
/usr/lib64/R/library/prefmod/DESCRIPTION
/usr/lib64/R/library/prefmod/INDEX
/usr/lib64/R/library/prefmod/Meta/Rd.rds
/usr/lib64/R/library/prefmod/Meta/data.rds
/usr/lib64/R/library/prefmod/Meta/features.rds
/usr/lib64/R/library/prefmod/Meta/hsearch.rds
/usr/lib64/R/library/prefmod/Meta/links.rds
/usr/lib64/R/library/prefmod/Meta/nsInfo.rds
/usr/lib64/R/library/prefmod/Meta/package.rds
/usr/lib64/R/library/prefmod/NAMESPACE
/usr/lib64/R/library/prefmod/NEWS
/usr/lib64/R/library/prefmod/NEWS.Rd
/usr/lib64/R/library/prefmod/NEWS.pdf
/usr/lib64/R/library/prefmod/R/prefmod
/usr/lib64/R/library/prefmod/R/prefmod.rdb
/usr/lib64/R/library/prefmod/R/prefmod.rdx
/usr/lib64/R/library/prefmod/data/Rdata.rdb
/usr/lib64/R/library/prefmod/data/Rdata.rds
/usr/lib64/R/library/prefmod/data/Rdata.rdx
/usr/lib64/R/library/prefmod/help/AnIndex
/usr/lib64/R/library/prefmod/help/aliases.rds
/usr/lib64/R/library/prefmod/help/paths.rds
/usr/lib64/R/library/prefmod/help/prefmod.rdb
/usr/lib64/R/library/prefmod/help/prefmod.rdx
/usr/lib64/R/library/prefmod/html/00Index.html
/usr/lib64/R/library/prefmod/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/prefmod/libs/prefmod.so
/V4/usr/lib64/R/library/prefmod/libs/prefmod.so
/usr/lib64/R/library/prefmod/libs/prefmod.so
